version: '3.5'

services:
  redis:
    image: redis:4-alpine
    restart: unless-stopped
  app:
    image: dynamic-tree-api:local
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    volumes:
      - '.:/usr/src/app'
      - rails5-usrlocal:/usr/local/
    depends_on:
      - redis
      - sidekiq
      - db
    environment:
      - REDIS_URL=redis://redis:6379/0
      - REDIS_PROVIDER=REDIS_URL
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: myincrediblefakepassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile-local
    image: dynamic-tree-api:local
    working_dir: /usr/src/app
    command: >
      sh -c "bundle &&
             bundle exec sidekiq"
    volumes:
      - '.:/usr/src/app'
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - REDIS_PROVIDER=REDIS_URL

volumes:
  rails5-usrlocal:
  postgres-data:

networks:
  local:

