
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: db
  username: postgres
  database: tree_api
  password: myincrediblefakepassword

test:
  <<: *default
  host: db
  username: postgres
  database: tree_api_test
  password: myincrediblefakepassword

production:
  <<: *default
  database: tree_api
